#!/bin/sh
# #############################################################################
#
#  (C) 2011 Dell Inc.  All rights reserved.
#
#  THIS SOFTWARE IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT IS
#  PROVIDED "AS IS" WITHOUT ANY WARRANTY, EXPRESS, IMPLIED OR OTHERWISE,
#  INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTY OF MERCHANTABILITY OR
#  FITNESS FOR A PARTICULAR PURPOSE OR ANY WARRANTY REGARDING TITLE OR
#  AGAINST INFRINGEMENT.  IN NO EVENT SHALL DELL BE LIABLE FOR ANY DIRECT,
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTUTUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
#  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
#  IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  This sample script is provided as an example only, and is not warranted
#  in any way by Dell; Dell disclaims any liability in connection therewith.
#  Dell provides no technical support with regard to content herein. For
#  more information on libraries and tools used in this example, refer to
#  applicable documentation
#
# #############################################################################
# Version 1.0

read -n 15 -p "New IP address (ENTER for default: ${WSENDPOINT}) ? " temp
[ ! "${temp}." = "." ] && export WSENDPOINT=${temp}
temp=
read -p "New user name (ENTER for default: ${WSUSER}) ? " temp
[ ! "${temp}." = "." ] && export WSUSER=${temp}
temp=
read -p "New user password (ENTER for default: ${WSPASS}) ? " temp
[ ! "${temp}." = "." ] && export WSPASS=${temp}
temp=

export WSSLCERT=cer-${WSENDPOINT}.cer
if [ ! -e ${WSSLCERT} ]; then
   echo "NOTE: please wait, acquiring server certificate..."
   ping -W 3 -c 2 ${WSENDPOINT} >/dev/null 2>&1
   if [ $? -eq 0 ]; then
      echo | openssl s_client -connect ${WSENDPOINT}:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >${WSSLCERT} 2>&1
      echo "NOTE: Certificate acquired and save to file ${WSSLCERT}"
   else
      echo "ERROR: failed to ping ${WSENDPOINT}, check connection and run again"
   fi
   $WSCOLORNORM
fi

