#!/bin/sh
##############################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Dell, Inc. nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL Dell, Inc. BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
##############################################################################
# Version 1.0

read -n 15 -p "New IP address (ENTER for default: ${WSENDPOINT}) ? " temp
[ ! "${temp}." = "." ] && export WSENDPOINT=${temp}
temp=
read -p "New user name (ENTER for default: ${WSUSER}) ? " temp
[ ! "${temp}." = "." ] && export WSUSER=${temp}
temp=
read -p "New user password (ENTER for default: ${WSPASS}) ? " temp
[ ! "${temp}." = "." ] && export WSPASS=${temp}
temp=

export WSSLCERT=cer-${WSENDPOINT}.cer
if [ ! -e ${WSSLCERT} ]; then
   echo "NOTE: please wait, acquiring server certificate..."
   ping -W 3 -c 2 ${WSENDPOINT} >/dev/null 2>&1
   if [ $? -eq 0 ]; then
      echo | openssl s_client -connect ${WSENDPOINT}:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >${WSSLCERT} 2>&1
      echo "NOTE: Certificate acquired and save to file ${WSSLCERT}"
   else
      echo "ERROR: failed to ping ${WSENDPOINT}, check connection and run again"
   fi
   $WSCOLORNORM
fi

